#!/bin/bash

file=$1
template=$2

echo "-- This file is automatically generated." > ${file}
echo "-- See https://github.com/Ellypse/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words" >> ${file}

echo "local dictionary = {}" >> ${file}

files=( "fr:frFR"
"en:enUS"
"de:deDE"
"es:esES"
"es:esMX"
"it:itIT"
"ru:ruRU")

for fileName in "${files[@]}" ; do
    KEY="${fileName%%:*}"
    VALUE="${fileName##*:}"
    echo "dictionary[\"${VALUE}\"] = {" >> ${file}
    awk '{ print "\""$0"\","}' ${KEY} >> ${file}
    echo "}" >> ${file}
done

cat ${template} >> ${file}
